### ISSUE TITLE
[PE-D][Tester A] Budget of $0 is accepted

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W11-2/tp#124]
When adding a customer or property if budget is set to 00000000, the value goes through the app instead of being rejected for being <$10000 as the result shown in the result box.

To reproduce the bug, set the budget parameter to 000000000 when adding a cust/prop

When adding prop with a budget of $0:
![image.png](https://raw.githubusercontent.com/chiayunrong/ped/main/files/52b05714-0187-4c95-b36b-2ce776e49b39.png)

When adding prop with a budget of $00000:

![image.png](https://raw.githubusercontent.com/chiayunrong/ped/main/files/344bce97-c88b-4389-876b-9ef275f06105.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: chiayunrong/ped#1

**Comment by jianrong7** [comment]
Will fix this and add test cases for this as well to safeguard.
