### ISSUE TITLE
[PE-D][Tester B] Back to top link on UG is not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W11-2/tp#125]
When I clicked the 'back to top' link below the Features and Interface Layout heading, nothing happened. Do check all the links inside the UG to make sure they work.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: itssisi/ped#2

**Comment by jianrong7** [comment]
Will fix this.

**Comment by jianrong7** [comment]
#167
