### ISSUE TITLE
[PE-D][Tester A] filtering works with 0000000 budget

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W11-2/tp#143]
If the budget is set to 000000 as per one of the bug reports earlier, the app is able to show when filtering for it.

![image.png](https://raw.githubusercontent.com/chiayunrong/ped/main/files/ba4eda76-763d-4425-81bf-a3d1593d31f5.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: chiayunrong/ped#9

**Comment by jianrong7** [comment]
Linked to #124 , will fix this along with #124 and add test cases for safeguards.

**Comment by jianrong7** [comment]
Close #187
