### ISSUE TITLE
[PE-D][Tester B] Filtering does not work. 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W11-2/tp#145]
`filtercust` did nothing to the list. It would be good to recheck all the functionalities of your features again. 

![Screenshot 2023-11-03 at 4.46.09 PM.png](https://raw.githubusercontent.com/itssisi/ped/main/files/574057d8-3f99-448f-9fc2-9cc6938bb266.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: itssisi/ped#8

**Comment by FerdiHS** [comment]
This issue is linked with #140, #156, and #157. 
Thank you for pointing that out! I will be working on that.
