### ISSUE TITLE
[PE-D][Tester A] Matchcust does not seem to work.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W11-2/tp#148]
When trying to match Phoebe in the picture below, I would expect with a budget of $200000, she should be able to match property 3 and 4. However, when i run matchcust 1 I get no results. I classified this as high severity because this is the main functionality of the app.

Before running command:
![image.png](https://raw.githubusercontent.com/chiayunrong/ped/main/files/ca967821-0ba0-4855-adb4-7209c67102c9.png)

After running command:
![image.png](https://raw.githubusercontent.com/chiayunrong/ped/main/files/f6607bd9-c700-4c34-9f12-c17bda624c27.png)

State of the app:

![image.png](https://raw.githubusercontent.com/chiayunrong/ped/main/files/2230f77c-2b03-42a4-a661-89f9bacbdb5a.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: chiayunrong/ped#11

**Comment by jianrong7** [comment]
Do check this @Chrainx 🙏
