### ISSUE TITLE
[PE-D][Tester C] Missing table of contents in UserGuide.md

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W11-2/tp#159]
Table of contents is rather crucial for easier navigation for users and creates structure for the entire user guide. However, it is missing now.

![image.png](https://raw.githubusercontent.com/limjunxian1/ped/main/files/f0bec0a6-5bf2-4449-9d12-b19ae306630e.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: limjunxian1/ped#9

**Comment by jianrong7** [comment]
Will fix this.

**Comment by jianrong7** [comment]
Same as #123

**Comment by jianrong7** [comment]
Same as #123
