### ISSUE TITLE
[PE-D][Tester C] Image not rendering properly in UserGuide.md

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W11-2/tp#160]
The image is not rendered properly here as shown below:

![image.png](https://raw.githubusercontent.com/limjunxian1/ped/main/files/2336d1e8-77bf-4310-90eb-43a4a0cf1a20.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: limjunxian1/ped#10

**Comment by jianrong7** [comment]
Fixed in #167
